.mode columns
.headers on

CREATE TRIGGER insertTrigger
AFTER INSERT ON Amizade
FOR EACH ROW
WHEN NOT EXISTS(SELECT * FROM Amizade A WHERE A.ID1=New.ID2 AND A.ID2=New.ID1)
BEGIN
	INSERT INTO Amizade(ID1, ID2) values(New.ID2, New.ID1); 
END;


CREATE TRIGGER deleteTrigger
AFTER DELETE ON Amizade
FOR EACH ROW
WHEN EXISTS(SELECT * FROM Amizade A WHERE A.ID1=old.ID2 AND A.ID2=old.ID1)
BEGIN
	DELETE FROM Amizade WHERE ID1=Old.ID2 aND ID2=Old.ID1;
END;

CREATE TRIGGER onUpdate
BEFORE UPDATE ON Amizade
BEGIN
	SELECT raise(ignore);
END;